### ISSUE TITLE
Linux graphics  #development

### ISSUE THREAD

**Issue by brmassa** [ProwlEngine/Prowl#161]
# **Describe the bug**
Opening a simple project in Linux, it fails on creating Textures

```
System.Exception: Platform does not support (D24_UNorm_S8_UInt) format with a (Sampled, DepthStencil Texture2D)
   at Prowl.Runtime.Texture.RecreateInternalTexture(TextureDescription description) in /Prowl/Prowl.Runtime/Rendering/Texture/Texture.cs:line 125
   at Prowl.Runtime.Texture..ctor(TextureDescription description) in /Prowl/Prowl.Runtime/Rendering/Texture/Texture.cs:line 64
   at Prowl.Runtime.Texture2D..ctor(UInt32 width, UInt32 height, UInt32 mipLevels, PixelFormat format, TextureUsage usage, TextureSampleCount sampleCount) in /Prowl/Prowl/Prowl.Runtime/Rendering/Texture/Texture2D.cs:line 72
   at Prowl.Runtime.RenderTexture..ctor(UInt32 width, UInt32 height, PixelFormat[] colorFormats, Nullable`1 depthFormat, Boolean sampled, Boolean enableRandomWrite, TextureSampleCount sampleCount) in /Prowl/Prowl/Prowl.Runtime/Rendering/Texture/RenderTexture.cs:line 168
   at Prowl.Editor.GameWindow.RefreshRenderTexture() in /Prowl/Prowl/Prowl.Editor/Editor/GameWindow.cs:line 66
   at Prowl.Editor.GameWindow..ctor() in /Prowl/Prowl/Prowl.Editor/Editor/GameWindow.cs:line 51
   at Prowl.Editor.Program.<>c__DisplayClass9_0.<Run>b__1() in /Prowl/Prowl/Prowl.Editor/Program.cs:line 93
   at Prowl.Runtime.Application.AppUpdate() in /Prowl/Prowl/Prowl.Runtime/Application.cs:line 110

```

then, this error on each frame:

```
Error in EditorWindow: Object reference not set to an instance of an object.
   at Prowl.Editor.GameWindow.Draw() in /Prowl/Prowl/Prowl.Editor/Editor/GameWindow.cs:line 82
   at Prowl.Editor.EditorWindow.ProcessFrame() in /Prowl/Prowl/Prowl.Editor/Editor/EditorWindow.cs:line 236
```

# **To Reproduce**
1. On Linux, create a blank project
2. Open the project
3. See error on console

**Comment by sinnwrig** [comment]
Fixed in commit 6277358
